// The built-in typefaces (ADR 0010), generated by `npm run typeface -- --builtins`
// from open-licensed fonts (tools/type/builtins.ts, OFL.txt). The first is the
// text rig's default. The HTML export swaps this module for one holding only
// the typefaces and characters a scene uses.

import type { Typeface } from '../typeface';
import { fraunces } from './fraunces';
import { instrumentSerif } from './instrument-serif';
import { instrumentSerifItalic } from './instrument-serif-italic';
import { inter } from './inter';
import { interBold } from './inter-bold';
import { interDisplay } from './inter-display';
import { jetbrainsMono } from './jetbrains-mono';

export const typefaces: readonly Typeface[] = [inter, interBold, interDisplay, instrumentSerif, instrumentSerifItalic, fraunces, jetbrainsMono];
